# Generated by Django 3.0.7 on 2020-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('text', models.CharField(max_length=2048)),
            ],
        ),
    ]
